apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-pongs
          persistentVolumeClaim:
            claimName: pongs-claim
      containers:
        - name: pingpong
          image: outisa/pingpong-application:9e695cdb5942cbf8ca0055cde0d1dc1b12abd507
          volumeMounts:
            - mountPath: /app/pongs
              name: shared-pongs
