apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mainapp-namespace
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-pongs
          persistentVolumeClaim:
            claimName: pongs-claim
      containers:
        - name: pingpong
          image: outisa/pingpong-application:f12090bf6dc7e371645c9b4dc4da644197ba17628
          volumeMounts:
            - mountPath: /app/pongs
              name: shared-pongs
