apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingpong-ing
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        backend:
          serviceName: pingpong-backend-svc
          servicePort: 2345