apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app
spec:
  template:
    metadata:
      name: pingpong-app-v1
    spec:
      containers:
        - image: outisa/pingpong-application:b4b0a47093f21e711ee963596ceb82d3c2569949
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD