apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgABp9YPJvEphaBijqkJxa32CJvF0d4LyGnJ1T4BKERY2nBlItdO8TmIKk59bru6dojnOp25uqme5Je07eOCCYxRkWNWgeXEHkLRW8fYBpuoI6t1gQIzyDfJTsamVKOK1vghVAcPCqLgF3O72Ny4Z3pptrp0evBsPKafWzR72AGLjogABwStvaihu8THOxUMVMb6JLzZGvIJKBmIUy9vJLkhnsCCFhN4q28tG/Uf7Vt3edphf6+U/OlTSAnJLl/MJBsNNFgzy54R/mFRYroaU+TDlR6n/jGs3LdZT5vHL0UaRNEh8f9BMZkohlTJXUSOOFpFurDDu7+xyqF5RlmgdpTYjDY9F1u2GofI6XGOmNcZ8b21/uCbqoaAcQ1ile+vxdabTXLjyvdi8cx+nKJWbXvJ6u27QQEJ0fLpC6bAD/c9p1Me6Uq3g3UgIiXclZry6H8lt/bpJSxUToGoWY5bVuegCNVvTh+P1ItulXaWkE5OR3v2bm/VdPcdsD0D1UgK20k2Nd/W+r+Vag1HsT/sSySLyfDYzTCtnl0XINm6OyCzU5ET3fKH/LK6jmrbqYHbhzSQMzGie8hgMxpyvSItIruJ84po7RuWL88huh3s9pLaOKoY4gs/q9Hfn6xigwhUzYiLu0yJpqhtWLgldJHh2ofGWYoDyaiw18vVHP7hn3xtFgwxpAD4sVth2FNPXU7yI6jUrQ8oLnd3
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default

