apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: mainapp-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBN17tgqxEdu5ctI6loymp9By10AaBexvXiyQ35aoZWynrpN2oF5msnSfdU5UQTWfg/xRwRLWPEkET0ibA9M9Ac59N58uLUzw3mQRFopcebWgj7tR/d0CZuyF6pd5fywiSuGzZ3M003cvelYWndgstQbgzx2JLLCH3PXhGqeILo/oidhqpwMRTFbjUmFHDWzGH3nR2mlWTiDs6PwFlFwpCyDinE19xlrCCj7g0MlVugmh0RtrtE/e7Ltef/nwnlH2uDL/UcCoFwgAjDlCuW4oHjpiAZbs5NUuQ6kMzp9u4oH+9TXNaldHhWt3DeYkkpCtrPWfMzRJsnuqrpwL21t46LfLI8KeKEqHKEXj5Ez+qPM/mqv582xsI78FHTsgEKJfVY/olAck21WT8SXAyCxduK9lcRWM4dPfO/PQOAw1ORKah/Ju30zTbswMqVCl40I80FO4BQbGYcNiJ9MLnpcUjpdit8fJX+PAKMvLmAxhMKS3uV2YlC+0K5xTv7JRb5Sp6LvYUvRQ2Nxg3dAekUEDh3dpSkKgqjkwWntCJBeVKcieSuxQxI+Xni44UjjAU3APA0s0cLpG89zxAF4jUUWNcph+3vVg6606fdYjpnSjNo54wlx6ndsUvKF4+p35yKUEG6Nm0ouEczo9+AkmIf9g1VfdCjUVtQjN9IJy7uXTtIohvGaqB+9uSj6CcV+5ZuDRRpnYTVbSbZLg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: mainapp-namespace

