apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBcJGFiNisFHfipJ3gGiOuP3RW3MdRpOFQqmhrSsBj+gMQeHYyxZ0uPqRO8UAIEaPO2ZZkABiysg+xXzRdjcLCKwGInpe45LZzoYNIEsbjcjBknDohXCVN8YpRifG12kqIgcqS4FKILeechpwVeiIbYQFi3h1MDaY0vEioXMaSeG+91yZv+siungjPSDJJwQck2sWN045+KbU7RJ1vMKW9cLdBuqiFYRwkDHMObvwJPT09iNG9Mo7DGaoWTCUbt24PEncvBcHKRsGq8l6tgXpz7adNGuKzqFZm099kgM0a7ajQq0zDKORnloMOExpZ6yxwGtrYZNUo7XYH0mIQsLZ3hZFXagJZVAxhrra7E9Ve11gcEbyVYVw1uFfToeJNzHCLs1j1LZVJJYbZPdglLIYCtdq5+05FXCrCj3TLRfEzMAMX1Ujba4+PFZDs7Jd+Lgz2FxFQJzxqambPl3Gdl7jVCeeEn3Oi1z60DLazoCqeRlqJZFtT3+0YXUxr4nI9q7LSqMJ/y7W/BHFPjpfeF2EbtEa0z9hl37HlUEJd88RWSWargk4ChS46IPvEX3csipF6DRScqfAz+tSko97JaCpVOBHz8eAh/WN5eiRlbqTmRJB1ERa30DdDbIlnUudPTukh8gVk8qCweMASRZIXQYvazwcjSzv0xgjJfB7ru679da5vrZ90t0xjrTxYOpkzHcwv6XpJBDcwD
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default

