apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: mainapp-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAE+ueXzFdWd6UdiymSbVqEJgKuuF0HHWIlMIsZw4kOQfmR+JP+9hMZmA4Jtwvf/48x6L6WDjFU/9M5iOs0wwbZrciHGGuw95MNi1Z7BRmXyDpKWMQT6XLM0hyB+4QHYZ/vSPvm1OmrX/l5eZoFQ357cdn33FekH5hKcLt3Eyd2kQhT2MmX0G8wyccUhxeao5eu3+UQJuVeN/ElDquhJymTRd8kEomUGOkaAlb05623QKEfVghseGXdZV46k5dNMlnRhZmCyjHsKKeQvyTOrkY+HPDFW3Q05eTgjEpUfmRlozGcBGRanR3O2elNirX/XV0szsblGDetZNV5cmZ8D5n9Zg/v9z9BdMEQJtqJ7JTOf2nIOWnxrvzVR3I14/1Io7n3cv5v5+07zZjfMC5iMM3Buc/QQv+LI0YDOWXpmB/GYWwkKB6kjfgMCrQxcGobSd66ZYQXUOBvt/uM48SZb5AKBj/yyClsMrmybzzX98R4/m+BCZhOhsTqv/+dYBuGxL0TgLnSZ7zth3rzT75L8igVNI1ZSbc6L6Di/vsueI2wcjVDYGVcJIlgb5jp1Xs15qvVY4eKpDov5/I2azLcbuNlzXQT+/FBkKMfGhUaROkM33UnaaPCrgs/tPHV3wyA1m6hVFB1G7qO+ni859FxP6RJuhlO/kCpnjkp16NqrsQ1D4jmPzuCPjxK3dQinhaoDhBsT96hlA8vOg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: mainapp-namespace

