apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAVmkB2IMIqT1iF48eZ0PVwg+q1ewz/hlmItKKaJNYx2jUD4XuyDuZfsohPwf73UDTG510y4eBlV81NrAN/IklRP1uYoR6t3T8nNddxi1xz/QxRU390lr20+J+VAfpeph4kFC9kV+pGAPeiYjt5ti/epi7PPbSiPNqtOGl2PUyMwJcr9zKjomSKcFHCCo8T985dJ1Wzz9AYEuOg3cnDM0fTEG/NAW5cwaJ/kYzjx7ZkTKu/RtA73M2lRYib4Eev/mv2yMMzvJAH+JyWqYcarc2CrvVb8/0uxzN40yEof19fptc4+Sl3fbz7nPPwyWm646URsDTPOu7sMzbcElhQWlnOSBgfPddEFGNajQdgfI4tu+ovVpVqBtUYpHvwCBAzh0nyRCJyepnYT+5rrETG+19RrFExHw2ptF6IlhVxpD/UVoKJi3crXDn0oejZjhqk25CGKT1zRLaKIyEsQE46vmnyuNawpI4N60DHxc7uQvOxfc9oaj99+cqOSusXaE8sfzo/RNyDbxdIxglButiiXwQI8+o00Qbt0+8wksO94vKoiWA5Y92RQOlR/PS+hKGxwpjhcgmm9d2VgvBq585LfpkM684YFdRXm1rFgLGoNNkdcxW+fif/wQZvLvUh1DJu+vo9DPvfe4i+MX9dkXuRrW4GyJjeUb3vodx9GOo3Yg46tDYwkXHuo6uR+dfWFkbbGl3zKYgVpx4M
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default

