apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBiVtYzPz4jenwRO/QQmJXbKuE2/s2xnV8U1xaR9s06+LZA/2JhQ/gaF7U3TkJgDYBjwXBejAcLEI0wdQ+MTntzKsjbtSw6d+X2DS0dmwCCp9tmhhL6ZGgoV61Pg5vWGuL9xEy+dRyTBNcLRXYS0uqxUJMkimUqHUWJssKN4xLkxERhIujdygfZ+w070fCIauCSsmHsO8M3WX8z5BYr8EhztLVABLjnNb9ccyNejPR/vPvAeZvOmdvqP/xsvkfeAh637Q1aXZDvJ7vDPz6MmeTnwoDAef1az0raFsexc+ZbktAW5B6oerYdS3UD0qwPy80belR1Ppx5DbebZMH3eLoHygI0nyiYXK20NtTvPqJGeu3yIqAT9yD33gRhJu33ffwA7GjjCHUQmEJz1JOOWvsYOBB2YnFgYcNqQOl/+kE6YZFcvBicloUZHzMS0c+VdmAc9/eVMAvNdtrDjNJSYQv4QtZpXI1+p76lKnKaIn/YnWi6Rv1aWugDE9enS6bG24P5ooxpISCv6OvIuYKuVrCMpPw9Y0SKF5kVJbuBq1ITSyC1cEAQQyDXaDW3MH/3Kx9J1uWq0z16cQ89cstpDf/Jt/LrK1pEBTIuHX2cmijkXq1BP9mybPLrzP3ntSXB3fzksa44e3dRLJAVqD088YhxkwJiZ0DY+q0AFjJIyZ0JIN8Dta4bfHvTkvtPbW9QJ0JTPKnzxO05
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default

